language: node_js
node_js:
- '8.4'
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- ng build --prod
after_success:
- firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
    on_failure: change
    on_success: change
before_install:
- openssl aes-256-cbc -K $encrypted_4fb3cb473dc2_key -iv $encrypted_4fb3cb473dc2_iv
  -in src/environments/environment.prod.ts.enc -out src/environments/environment.prod.ts -d
